volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: 'nextcloud-db'
    volumes:
      - db:/docker/appdata/postgresql/nextcloud-data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      
  app:
    container_name: 'nextcloud-app'
    image: nextcloud:production-apache
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/docker/appdata/nextcloud-app
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db

  redis:
    container_name: 'redis'
    image: redis:8.0-M02-alpine
    restart: always